[alias]
surfpool-install = "install --path crates/cli --locked --force --features supervisor_ui --features version_check --features sqlite"
surfpool-install-dev = "install --path crates/cli --locked --force --features supervisor_ui --features sqlite"
# useful for local builds that point to local txtx crates - prevents conflicts with the supervisor_ui feature
surfpool-install-minimal = "install --path crates/cli --locked --force"
